;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        emmet-expand-line
        end-of-visual-line
        fill-paragraph
        indent-for-tab-command
        kill-region
        kmacro-end-or-call-macro
        nxml-electric-slash
        nxml-finish-element
        switch-to-buffer
        un-indent-by-removing-4-spaces
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        beginning-of-visual-line
        comint-send-input
        end-of-buffer
        goto-line
        suspend-frame
        yank-rectangle
        ))
